Fix CI / deployment pipeline
Deployments were stuck due to fairly consistent CI test failures
(with occasional passing), like this:
https://github.com/alphagov/whitehall/actions/runs/19062938999/job/54455037559

```
Error:
AttachmentDeletionIntegrationTest::attachment deletion::given a draft document with multiple file attachments::when one attachment is deleted#test_0001_deletes the corresponding asset in Asset Manager when the edition is published:
ActionView::Template::Error: undefined method `pluralize' for nil
    app/helpers/admin/edition_actions_helper.rb:74:in `block in configurable_document_type_options'
    app/helpers/admin/edition_actions_helper.rb:70:in `each'
    app/helpers/admin/edition_actions_helper.rb:70:in `filter_map'
    app/helpers/admin/edition_actions_helper.rb:70:in `configurable_document_type_options'
    app/helpers/admin/edition_actions_helper.rb:80:in `combined_list_of_document_types'
    app/helpers/admin/edition_actions_helper.rb:16:in `filter_edition_type_opt_groups'
    app/views/admin/editions/_filter_options.html.erb:95
    app/views/admin/editions/_filter_options.html.erb:8
    app/views/admin/editions/index.html.erb:7
    app/controllers/admin/editions_controller.rb:48:in `index'
    test/integration/attachment_deletion_integration_test.rb:55:in `block (4 levels) in <class:AttachmentDeletionIntegrationTest>'
bin/rails test test/integration/attachment_deletion_integration_test.rb:36
```

This stems from a recent change to edition_actions_helper:
https://github.com/alphagov/whitehall/pull/10782/files#diff-19b825cccb2a0db1431d8e8154409d6334912b8a1e3e22def2300cd980be542dR74

The change made the (very fair) assumption that every configurable
document type returned by `ConfigurableDocumentType.all` has
a "title" property (which drives the `label` method).

We tracked down the test failure to this one unit test in
standard_edition_rules_test.rb which overrides the document types
returned by `all` to return _invalid_ content type definitions.
Namely:

1. No `title` property at the root (it was incorrectly set to
   be a child property of `schema`)
2. Unnecessary additional JSON schema properties (a relic from
   before we decided to move away from JSON schema in
   [ADR 8](https://github.com/alphagov/whitehall/blob/main/docs/adr/0008-drop-json-schema-for-document-configuration.md)

This commit fixes those issues.

CI would _occasionally_ pass, if the above test were the last one
to run. But if the above test were to run _before_ another test
which then exercises the edition_action_helper views, then CI
would fail as we'd be attempting to call `pluralize` on a `nil`
value.