Update data migration
The data migration previously failed as the HTML attachment couldn't be
found by the slug. This edition only has one attachment so just calling
`.last` is sufficient.

```
Error:
E, [2021-10-11T15:52:31.671483 #4438] ERROR -- : Migration failed due to undefined method `update!' for nil:NilClass
16:52:31 E, [2021-10-11T15:52:31.671577 #4438] ERROR -- :   /data/vhost/whitehall-admin/releases/20211011150810/db/data_migration/20211011140013_reslug_publication.rb:10:in `block in run'
```