Upgrade to govuk_app_config 4.6
govuk_app_config 4.6 includes automatic ignoring of the Sidekiq internal
exception: Sidekiq::JobRetry::Skip so this can be removed from our code.