Remove Style/MethodMissing from .rubocop.yml
This has been split, so remove it, and switch to disabling the checks
in the individual files.

  Error: The `Style/MethodMissing` cop has been split into
  `Style/MethodMissingSuper` and `Style/MissingRespondToMissing`.