Define admin routes for StatisticalDataSet to avoid exception.
We were seeing the following exception in production:

    A ActionView::Template::Error occurred in editorial_remarks#new:

     undefined method `admin_statistical_data_set_editorial_remarks_path'
    for #<#<Class:0x00000009a601b8>:0x0000000a9e3298>
     actionpack (3.1.7)
    lib/action_dispatch/routing/polymorphic_routes.rb:127:in
    `polymorphic_url'

    -------------------------------
    Request:
    -------------------------------

     * URL       :
     * https://whitehall-admin.production.alphagov.co.uk/government/admin/editions/16336/editorial_remarks/new
     * IP address: 127.0.0.1
     * Parameters: {"action"=>"new",
     * "controller"=>"admin/editorial_remarks", "edition_id"=>"16336"}

This was because `Admin::EditionRoutesHelper::EDITION_TYPES` did not
include `StatisticalDataSet`.

I'd have like to have found a better place to add this test, but
couldn't find anywhere sensible.