Fix checking of environment for scheduled job
We were seeing a failure to deploy and an error[1] of:

```
bundler: failed to load command: whenever
...
NoMethodError: undefined method `present?' for 12:Integer
```
because we weren't loading the right `.present?` method from ActiveSupport.

[1] https://deploy.integration.publishing.service.gov.uk/job/Deploy_App/36679/console