Remove Style/MethodMissing from .rubocop.yml
This has been split, so lets remove it and see what happens:

  Error: The `Style/MethodMissing` cop has been split into
  `Style/MethodMissingSuper` and `Style/MissingRespondToMissing`.