Temporarily persist - then roll back - when previewing changes
The presenters often rely on associations being persisted. They
don't just fetch `{some_edition}.featured_documents` (that could
be initialized in memory), they then chain additional method calls
like `.where`, to narrow down to a subset. We could in theory
patch every helper method so that it works with in-memory
associations but it's cleaner to just persist the records, let
everything work as it actually would in real life, and compare
_those_ payloads.

NB, the Document creation is required to support persisted-driven
preview of non-Documents being passed to `compare_payloads`,
otherwise there's an issue with assigning the slug:

```
NoMethodError: undefined method `live_edition_id' for nil (NoMethodError)

    return unless new_record? && document.live_edition_id
                                         ^^^^^^^^^^^^^^^^
from /govuk/whitehall/app/models/concerns/edition/identifiable.rb:67:in `set_slug_override'
```