Use a fallback thumbnail if PDF thumbnailing fails.
It's possible for malformed PDFs to crash the thumbnailing process,
which ultimately prevents the attachment from being uploaded.

I could not replicate the actual crash seen locally, because my
version of Ghostscript is newer than the one on the server (9.05 vs
8.71), but I believe the ultimate cause was a font which should've
been embeded in the PDF, but wasn't:

    deploy@whitehall-admin-preview:/var/apps/whitehall-admin$ gs "/mnt/apps/whitehall-admin/tmp_bis_attachments/81495deea5b8257ef0d88dfc1946fb24b8a7d752/11-1036-employment-earning-outcomes-
    train-to-gain-extension.pdf"
    GPL Ghostscript 8.71 (2010-02-10)
    Copyright (C) 2010 Artifex Software, Inc.  All rights reserved.
    This software comes with NO WARRANTY: see the file PUBLIC for details.
    Warning: the map file cidfmap was not found.
    Processing pages 1 through 49.
    Page 1
    Can't find CID font "Arial".
    Substituting CID font /Adobe-Identity for /Arial, see doc/Use.htm#CIDFontSubstitution.
    The substitute CID font "Adobe-Identity" is not provided either. Will exit with error.
    Error: /undefined in findresource
    Operand stack:
       --dict:10/19(L)--   C2_2   1   --dict:5/5(L)--   --dict:5/5(L)--   Arial,Bold   --dict:9/12(ro)(G)--   --nostringval--   CIDFontObject   --dict:7/7(L)--   --dict:7/7(L)--   Ad
    obe-Identity
    Execution stack:
       %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped
    _push   1878   1   3   %oparray_pop   1877   1   3   %oparray_pop   1861   1   3   %oparray_pop   --nostringval--   --nostringval--   2   1   49   --nostringval--   %for_pos_int_
    continue   --nostringval--   --nostringval--   --nostringval--   --nostringval--   %array_continue   --nostringval--   false   1   %stopped_push   --nostringval--   %loop_continu
    e   --nostringval--   --nostringval--   --nostringval--   --nostringval--   --nostringval--   --nostringval--   %array_continue   --nostringval--   --nostringval--   --nostringva
    l--   --nostringval--   --nostringval--   %loop_continue   --nostringval--   --nostringval--   --nostringval--   %loop_continue
    Dictionary stack:
       --dict:1150/1684(ro)(G)--   --dict:1/20(G)--   --dict:75/200(L)--   --dict:75/200(L)--   --dict:108/127(ro)(G)--   --dict:288/300(ro)(G)--   --dict:22/25(L)--   --dict:6/8(L)-
    -   --dict:26/40(L)--
    Current allocation mode is local
    Last OS error: 2
    GPL Ghostscript 8.71: Unrecoverable error, exit code 1

Rather than crash and fail to upload the attachment, we can provide
a default thumbnail. Ideally I would like to make such attachments
"not-thumbnailable", but I don't think carrierwave permits this
kind of dynamic versioning. The conditional mechanism it does
provide would need to actually attempt the PDF conversation every
time an attachment was loaded to determine whether or not the
attachment "has" a thumbnail.

I've changed the exception raised into a log warn message, so we
will still be able to see that something undesirable happened.