Fix TopicalEvent publishing-api datetime error
When republishing these in integration, we were seeing an error:

  NoMethodError: undefined method `to_datetime' for nil:NilClass

This is because the checks where each checking the wrong thing.

I've added a test against regressions. I can't test the other way around
because the TopicalEvent model prevents that.