Add validation for specialist guide heading hierarchy.
We were seeing the following exception in production :-

    A ActionView::Template::Error occurred in specialist_guides#show

    undefined method `[]' for nil:NilClass
    app/helpers/govspeak_helper.rb:69:in `block in
govspeak_header_heirarchy'

This fixes the existing specialist guide editions with this problem and
introduces validation to ensure that it cannot happen again.