Bump MySQL2 to 0.5.3
Upgrading MySQL2 to prevent the following error when running the tests:

```
LoadError: Error loading the 'mysql2' Active Record adapter. Missing a gem it depends on? can't activate mysql2 (~> 0.5), already activated mysql2-0.4.10. Make sure all dependencies are added to Gemfile.
```