Make DB migration idempotent
We were seeing this failure on staging:

```
== 20250314094940 MakeEditionIdUniqueOnLinkCheckerApiReports: migrating =======
-- remove_foreign_key(:link_checker_api_reports, :editions)
bin/rails aborted!
StandardError: An error has occurred, all later migrations canceled: (StandardError)
Table 'link_checker_api_reports' has no foreign key for editions
/app/db/migrate/20250314094940_make_edition_id_unique_on_link_checker_api_reports.rb:5:in `change'
Caused by:
ArgumentError: Table 'link_checker_api_reports' has no foreign key for editions (ArgumentError)
            raise(ArgumentError, "Table '#{from_table}' has no foreign key for #{to_table || options}")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/app/db/migrate/20250314094940_make_edition_id_unique_on_link_checker_api_reports.rb:5:in `change'
Tasks: TOP => db:migrate
```

This didn't happen on Integration.

It's possible that the branch had been deployed to and run on
staging, and now on merge, we're encountering an error. So
tweaking the migration to run idempotently.

Trello: https://trello.com/c/tmnht4P1